name: Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set version
      id: set_version
      run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

    - name: Build
      run: make

    - name: List files
      run: pwd

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: cdecrypt
        path: /home/runner/work/cdecrypt/cdecrypt/cdecrypt
